# 1. Demonstrate three different methods for creating identical 2D arrays inNumPy.Provide the code for each method and the final output after each method

In [61]:
import numpy as np

# Using nested lists
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Method 1:\n", array_1)

# Using arange and reshape
array_2 = np.arange(1, 10).reshape(3, 3)
print("\nMethod 2:\n", array_2)


# Using ones and addition
array_3 = np.ones((3,3), dtype=int)
for i in range(3):
    for j in range(3):
        array_3[i, j] += i*3 + j
print("\nMethod 3:\n", array_3)

Method 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Method 2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Method 3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 100 and Reshape that 1D array into a 2D array


In [62]:
# Using linspace and reshape
array_4 = np.linspace(1, 10, 100).reshape(10, 10)
print("\nResult:\n", array_4)


Result:
 [[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818

#3.Explain the following terms:
# - The difference in np.array, np.asarray and np.asanyarray
# - The difference between Deep copy and shallow copy

In [63]:
#Difference in np.array, np.asarray and np.asanyarray
#np.array: This is the most common way to create an array in NumPy. It creates a new array object, copying the data from the input.  It accepts lists, tuples, other arrays, etc.
#np.asarray:  Similar to np.array but it will not create a copy if the input is already a NumPy array. If the input is a different data type, it converts it into an array, creating a new array object.
#np.asanyarray: Similar to np.asarray, but it also accepts other array-like objects without creating a copy. It's useful when you need to work with existing array objects directly.  If the input is already a NumPy array, it returns a reference to the original without creating a new object.

# Demonstration
#1
arr = [1,2,3]
arr_np = np.array(arr) # creates a new array object
arr_asarray = np.asarray(arr) # creates a new array object
arr_asanyarray = np.asanyarray(arr) # creates a new array object

#2
arr_np2 = np.array(arr_np) # creates a new array object
arr_asarray2 = np.asarray(arr_np) # does not create a copy since it's already a numpy array
arr_asanyarray2 = np.asanyarray(arr_np) # does not create a copy

#Deep Copy vs Shallow copy
#Deep copy: Creates a completely independent copy of the array and its data.  Modifications to the copy do not affect the original and vice-versa.  This consumes more memory but ensures data integrity.
#Shallow copy: Creates a new array object, but the new array's data points to the same memory location as the original array. Changing elements in the copy will affect the original, and vice-versa. This saves memory but can lead to unexpected modifications.

# Demonstrating deep copy
original_array = np.array([1, 2, 3])
deep_copy = original_array.copy() # Creates a new array object and copies the data
deep_copy[0] = 99
print("Original Array (Deep Copy):", original_array)  # Original remains unchanged
print("Deep Copy:", deep_copy)

# Demonstrating shallow copy
original_array_2 = np.array([1, 2, 3])
shallow_copy = original_array_2.view() # creates new array object but data points to same memory
shallow_copy[0] = 99
print("Original Array (Shallow Copy):", original_array_2) # Original changes since data was not copied.
print("Shallow Copy:", shallow_copy)

Original Array (Deep Copy): [1 2 3]
Deep Copy: [99  2  3]
Original Array (Shallow Copy): [99  2  3]
Shallow Copy: [99  2  3]


# 4.Generate a 3X3 array with random floating-point numbers between 5 and 20.Then, round each number in the array to 2 decimal places.

In [64]:
import numpy as np

# Generate a 3x3 array with random floating-point numbers between 5 and 20
random_array = np.random.uniform(5, 20, size=(3, 3))

print(random_array)

# Round each number to 2 decimal places
rounded_array = np.round(random_array, 2)

print(rounded_array)

[[ 7.66487746  9.87047413 18.59761191]
 [14.17146441  8.648356   14.62625032]
 [ 9.02402098 17.35648814 14.54159134]]
[[ 7.66  9.87 18.6 ]
 [14.17  8.65 14.63]
 [ 9.02 17.36 14.54]]


# 5.Create a NumPy array with random integers Petween 1 and 10 of shape (5,6).After creating the array perform the following operations:
# a)Extract all even integers from array.
# b)Extract all odd integers from array.

In [65]:
import numpy as np

# Create a 5x6 array with random integers between 1 and 10
random_array = np.random.randint(1, 11, size=(5, 6))

print("Original array:\n", random_array)

# a) Extract all even integers
even_numbers = random_array[random_array % 2 == 0]
print("\nEven numbers:\n", even_numbers)

# b) Extract all odd integers
odd_numbers = random_array[random_array % 2 != 0]
print("\nOdd numbers:\n", odd_numbers)

Original array:
 [[ 7  6  5 10  9  3]
 [ 7  1  1  5  9  8]
 [ 8  4  9  8  4 10]
 [10  7  4  8 10  5]
 [ 6  9  7  9  5  7]]

Even numbers:
 [ 6 10  8  8  4  8  4 10 10  4  8 10  6]

Odd numbers:
 [7 5 9 3 7 1 1 5 9 9 7 5 9 7 9 5 7]


# 6.Create a 3D NumPy array of shape (3,3,3) containing random integers between 1 and 10.Perform the following operations:
#a) Find the indices of the maximum values along each depth level (third axis).
# b) Perform element-wise multiplication of between both array.

In [66]:
import numpy as np

# Create a 3D NumPy array of shape (3, 3, 3) with random integers between 1 and 10
array_3d = np.random.randint(1, 11, size=(3, 3, 3))
print("Original 3D array:\n", array_3d)

# a) Find the indices of the maximum values along each depth level (third axis)
indices_of_max = np.argmax(array_3d, axis=2)
print("\nIndices of maximum values along each depth level:\n", indices_of_max)

# b) Perform element-wise multiplication of the array with itself
elementwise_product = array_3d * array_3d # or np.multiply(array_3d, array_3d)
print("\nElement-wise product of the array with itself:\n", elementwise_product)

Original 3D array:
 [[[ 7 10 10]
  [ 7  9  4]
  [ 3  1  5]]

 [[ 2  2  2]
  [ 7  2  6]
  [ 5  7  3]]

 [[ 8  3  3]
  [ 6 10  5]
  [ 6  3  8]]]

Indices of maximum values along each depth level:
 [[1 1 2]
 [0 0 1]
 [0 1 2]]

Element-wise product of the array with itself:
 [[[ 49 100 100]
  [ 49  81  16]
  [  9   1  25]]

 [[  4   4   4]
  [ 49   4  36]
  [ 25  49   9]]

 [[ 64   9   9]
  [ 36 100  25]
  [ 36   9  64]]]


# 7.Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and convert it to a numeric data type.Also display the table attributes and data types of each column.

In [67]:
import pandas as pd
import numpy as np

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('/content/data/PeopleData.csv')

# Clean and transform the 'Phone' column
def clean_phone_number(phone_number):
    if isinstance(phone_number, str):
        numeric_chars = ''.join(filter(str.isdigit, phone_number))
        if numeric_chars:
            return int(numeric_chars)
    return np.nan  # Or another appropriate value for invalid phone numbers

df['Phone'] = df['Phone'].apply(clean_phone_number)

# Display table attributes and data types
print("Table Attributes and Data Types:")
print(df.info())

print("\nDataFrame Head:")
df['Phone'].astype(str)

Table Attributes and Data Types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Index          1000 non-null   int64  
 1   User Id        1000 non-null   object 
 2   First Name     1000 non-null   object 
 3   Last Name      1000 non-null   object 
 4   Gender         1000 non-null   object 
 5   Email          1000 non-null   object 
 6   Phone          979 non-null    float64
 7   Date of birth  1000 non-null   object 
 8   Job Title      1000 non-null   object 
 9   Salary         1000 non-null   int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 78.2+ KB
None

DataFrame Head:


0            8571398239.0
1                     nan
2            5997820605.0
3                     nan
4        39041716353010.0
              ...        
995           217752933.0
996      11497107799721.0
997    1750774412833265.0
998          9152922254.0
999      79752542467259.0
Name: Phone, Length: 1000, dtype: object

# 8.Perform the following tasks using people dataset:
#a) Read the 'data.csv' file using pandas, skipping the first 50 rows.
#b) Only read the columns: 'Last Name', ‘Gender’, ’Email’, ‘Phone’ and ‘Salary’ from the file.
#c) Display the first 10 rows of the filtered dataset.
#d) Extract the ‘Salary’' column as a Series and display its last 5 values

In [68]:
df_orig = pd.read_csv('/content/data/PeopleData.csv', usecols=['Last Name', 'Gender', 'Email', 'Phone', 'Salary'])

df = df_orig.tail(-50)
print(df.head(10))

salary_series = df['Salary']
print(salary_series.tail(5))

   Last Name  Gender                       Email                   Phone  \
50    Zavala    Male        pamela64@example.net  001-859-448-9935x54536   
51     Carey  Female   dianashepherd@example.net    001-274-739-8470x814   
52     Hobbs  Female   ingramtiffany@example.org        241.179.9509x498   
53    Reilly    Male  carriecrawford@example.org       207.797.8345x6177   
54    Conrad    Male  fuentesclaudia@example.net    001-599-042-7428x143   
55      Cole    Male      kaneaudrey@example.org            663-280-5834   
56   Donovan    Male   rebekahsantos@example.net                     NaN   
57    Little  Female         craig28@example.com       125.219.3673x0076   
58    Dawson  Female  connercourtney@example.net      650-748-3069x64529   
59      Page    Male  harrygallagher@example.com        849.500.6331x717   

    Salary  
50   80000  
51   70000  
52   60000  
53  100000  
54   50000  
55   85000  
56   65000  
57   60000  
58   60000  
59   60000  
995     90000
996   

# 9.Filter and select rows from the PeopleDataset, where the "Last Name" column contains the name 'Duke', 'Gender' column contains the word Female and ‘Salary’ should be less than 85000

In [69]:

# Filter the DataFrame
filtered_df = df_orig[
    (df_orig['Last Name'].str.contains('Duke', case=False)) &
    (df_orig['Gender'] == 'Female') &
    (df_orig['Salary'] < 85000)
]

print(filtered_df)

    Last Name  Gender                     Email                   Phone  \
45       Duke  Female       diana26@example.net  001-366-475-8607x04350   
210      Duke  Female       robin78@example.com            740.434.0212   
457      Duke  Female  perryhoffman@example.org     +1-903-596-0995x489   
729      Duke  Female   kevinkramer@example.net            982.692.6257   

     Salary  
45    60000  
210   50000  
457   50000  
729   70000  


# 10.Create a 7X5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

---



In [70]:
import pandas as pd
import numpy as np

# Create a series of 35 random integers between 1 and 6
data = pd.Series(np.random.randint(1, 7, size=35))

# Reshape the series into a 7x5 DataFrame
df = pd.DataFrame(data.values.reshape(7, 5))

# Print the DataFrame
print(df)

   0  1  2  3  4
0  1  4  6  5  6
1  6  1  2  1  1
2  2  6  4  2  1
3  6  5  1  5  4
4  2  5  1  6  1
5  5  2  6  6  6
6  3  3  2  5  1
